
os: Visual Studio 2015

environment:
  matrix:
    - channel: stable
      target: x86_64-pc-windows-msvc
    - channel: beta
      target: x86_64-pc-windows-msvc
    - channel: nightly
      target: x86_64-pc-windows-msvc

matrix:
  allow_failures:
    - channel: nightly


# Install the rust target and channel defined by the
# configuration matrix.
install:
  - git submodule update --init
  - appveyor DownloadFile https://win.rustup.rs/ -FileName rustup-init.exe
  - rustup-init -yv --default-toolchain %channel% --default-host %target%
  - set PATH=%PATH%;%USERPROFILE%\.cargo\bin
  - rustc -vV
  - cargo -vV
  - rustup component add clippy
  - py -0p

build: false

test_script:
  - cargo test --verbose
  - cargo clippy --all-targets --all-features -- -D warnings
