[package]
name = "build-tools"
version = "0.1.0"
authors = ["Phantomical", "Agustin Godnic"]
edition = "2018"

[dependencies]
bindgen = "0.53"
fs_extra = "1.1"
num_cpus = "1.10"
target-lexicon = "0.10"

syn = { version = "1.0", features = [ "full" ] }
quote = "1.0"
proc-macro2 = "1.0"
