// These are translation from autogenerated files.
// They may be different for different builds
// (but I hope not)

use xed_interface::*;

pub(crate) unsafe fn xed3_operand_get_mode(d: *const xed_decoded_inst_t) -> xed_bits_t {
    return (*d)._operands.mode as xed_bits_t;
}

pub(crate) unsafe fn xed3_operand_get_smode(d: *const xed_decoded_inst_t) -> xed_bits_t {
    return (*d)._operands.smode as xed_bits_t;
}

pub(crate) unsafe fn xed3_operand_get_chip(d: *const xed_decoded_inst_t) -> xed_bits_t {
    return (*d)._operands.chip as xed_bits_t;
}

pub(crate) unsafe fn xed3_operand_set_chip(d: *mut xed_decoded_inst_t, opval: xed_chip_enum_t) {
    (*d)._operands.chip = opval as u8;
}

pub(crate) unsafe fn xed3_operand_get_uimm1(d: *const xed_decoded_inst_t) -> u8 {
    return (*d)._operands.imm1;
}
