/* automatically generated by rust-bindgen */

extern "C" {
    ///@ingroup INIT
    /// Returns a string representing XED svn commit revision and time stamp.
    pub fn xed_get_version() -> *const ::std::os::raw::c_char;
}
extern "C" {
    ///@ingroup INIT
    /// Returns a copyright string.
    pub fn xed_get_copyright() -> *const ::std::os::raw::c_char;
}
